import { inputForm } from './variations';
import { reactDemo } from './reactDemo';

export default {
    title: 'Form',
    slug: 'form',
    description: 'Buttons are used for directing user to another action',
    'last-updated': '9/20/21',
    image: '/component_icons/form.svg',
    imageColor: '/component_icons/form_ro.svg',
    variations: [
        {
            name: 'Input Form',
            description: 'Use the base class <code class="pier-body-text__inline-code">pier-form</code> to create a default form',
            markup: inputForm,
            dark: false,
        },
    ],
    'react-import': `import { Form } from "pier-design-system"`,
    'react-components': [
        {
            name: '<Button>',
            props: [
                {
                    name: 'children',
                    type: 'node',
                    isRequired: true,
                    default: '',
                    description: 'The content to be displayed inside of the button.',
                },
                {
                    name: 'size',
                    type: `string; one of: "xs", "sm", "md", "lg"`,
                    isRequired: false,
                    default: 'md',
                    description: 'Set the size of the button.',
                },
                {
                    name: 'type',
                    type: 'string',
                    isRequired: false,
                    default: '',
                    description: 'Add type onto the button.',
                },
                {
                    name: 'value',
                    type: 'string',
                    isRequired: false,
                    default: '',
                    description: '',
                },
                {
                    name: 'icon',
                    type: 'string',
                    isRequired: false,
                    default: '',
                    description: `Use a font awesome class to display an icon inside of the button. Ex: "fas fa-atom"`,
                },

                {
                    name: 'disabled',
                    type: 'bool',
                    isRequired: false,
                    default: false,
                    description: "Set the button to it's disabled state.",
                },
                {
                    name: 'dark',
                    type: 'bool',
                    isRequired: false,
                    default: false,
                    description: "Set the button to it's dark theme.",
                },
                {
                    name: 'pill',
                    type: 'bool',
                    isRequired: false,
                    default: 'false',
                    description: 'Makes the button pill',
                },
                {
                    name: 'error',
                    type: 'bool',
                    isRequired: false,
                    default: 'false',
                    description: 'Makes the button error',
                },
                {
                    name: 'secondary',
                    type: 'bool',
                    isRequired: false,
                    default: 'false',
                    description: 'Makes a secondary button',
                },
                {
                    name: 'onClick',
                    type: 'func',
                    isRequired: false,
                    default: '',
                    description: 'Event handler on button click',
                },
                {
                    name: 'className',
                    type: 'string',
                    isRequired: false,
                    default: '',
                    description: 'Add classes onto the button',
                },
                {
                    name: 'style',
                    type: 'object',
                    isRequired: false,
                    default: '',
                    description: 'Add extra styling onto the button.',
                },
                {
                    name: 'iconStyle',
                    type: 'object',
                    isRequired: false,
                    default: '',
                    description: 'Add extra styling onto the icon.',
                },
                {
                    name: 'onMouseEnter',
                    type: 'func',
                    isRequired: false,
                    default: '',
                    description: 'Event handler on button hover in',
                },
                {
                    name: 'onMouseLeave',
                    type: 'func',
                    isRequired: false,
                    default: '',
                    description: 'Event handler on button hover out',
                },
                {
                    name: 'onBlur',
                    type: 'func',
                    isRequired: false,
                    default: '',
                    description: 'Event handler on button when focus has left the button',
                },
                {
                    name: 'onFocus',
                    type: 'func',
                    isRequired: false,
                    default: '',
                    description: 'Event handler on button when on focus',
                },
            ],
        },
    ],
    'react-demo': reactDemo,
};
