import { base, sizes, styles, disabled, pill, staticTag, dark } from './variations';
import { reactDemo } from './reactDemo';

export default {
    title: 'Tag',
    slug: 'tag',
    description: 'A short piece of interactive text.',
    'last-updated': '9/21/21',
    image: '/component_icons/tag.svg',
    imageColor: '/component_icons/tag_ro.svg',
    variations: [
        {
            name: 'Base',
            description: `Use the base class <code class="pier-body-text__inline-code">pier-tag</code> to create a Tag element.`,
            markup: base,
            dark: false,
        },
        {
            name: 'Sizes',
            description: `Use the modifier classes <code class="pier-body-text__inline-code">pier-tag--sm</code>, <code class="pier-body-text__inline-code">pier-tag--md</code>, or <code class="pier-body-text__inline-code">pier-tag--lg</code> to change the size of the Tag.`,
            markup: sizes,
            dark: false,
        },
        {
            name: 'Styles',
            description: `Use the modifier class <code class="pier-body-text__inline-code">pier-tag--hero</code> to change the theme of the Tag.`,
            markup: styles,
            dark: false,
        },
        {
            name: 'Disabled',
            description: `Use the modifier class <code class="pier-body-text__inline-code">pier-tag--disabled</code> to change the state of the Tag to disabled.`,
            markup: disabled,
            dark: false,
        },
        {
            name: 'Pill',
            description: `Use the modifier class <code class="pier-body-text__inline-code">pier-tag--pill</code> to change the the style of the Tag to pilled.`,
            markup: pill,
            dark: false,
        },
        {
            name: 'Static',
            description: `Use the modifier class <code class="pier-body-text__inline-code">pier-tag--static</code> to change the state of the Tag to static.`,
            markup: staticTag,
            dark: false,
        },
        {
            name: 'Dark',
            description: `Use the modifier class <code class="pier-body-text__inline-code">pier-tag--dark</code> to change the style of the Tag for dark UI themes.`,
            markup: dark,
            dark: true,
        },
    ],
    'react-import': `import { Tag } from "pier-design-system"`,
    'react-components': [
        {
            name: '<Tag>',
            props: [
                {
                    name: 'children',
                    type: 'node',
                    isRequired: true,
                    default: '',
                    description: 'The text to be displayed inside of the open Tag.',
                },
                {
                    name: 'theme',
                    type: `string; one of: "default", "hero"`,
                    isRequired: false,
                    default: 'default',
                    description: 'Set the theme of the Tag.',
                },
                {
                    name: 'size',
                    type: `string; one of: "sm", "md", "lg"`,
                    isRequired: false,
                    default: 'md',
                    description: 'Set the size of the Tag.',
                },
                {
                    name: 'disabled',
                    type: 'bool',
                    isRequired: false,
                    default: false,
                    description: "Set the Tag to it's disabled state.",
                },
                {
                    name: 'isStatic',
                    type: 'bool',
                    isRequired: false,
                    default: false,
                    description: "Set the Tag to it's static state.",
                },
                {
                    name: 'dark',
                    type: 'bool',
                    isRequired: false,
                    default: false,
                    description: "Set the Tag to it's dark theme.",
                },
                {
                    name: 'onClick',
                    type: 'function',
                    isRequired: false,
                    default: '',
                    description: 'Execute the defined function on Tag click.',
                },
                {
                    name: 'onMouseEnter',
                    type: 'function',
                    isRequired: false,
                    default: '',
                    description: 'Execute the defined function on Tag mouse enter.',
                },
                {
                    name: 'onMouseLeave',
                    type: 'function',
                    isRequired: false,
                    default: '',
                    description: 'Execute the defined function on Tag mouse leave.',
                },
                {
                    name: 'onFocus',
                    type: 'function',
                    isRequired: false,
                    default: '',
                    description: 'Execute the defined function on Tag focus.',
                },
                {
                    name: 'onBlur',
                    type: 'function',
                    isRequired: false,
                    default: '',
                    description: 'Execute the defined function on Tag blur.',
                },
                {
                    name: 'className',
                    type: 'string',
                    isRequired: false,
                    default: '',
                    description: 'Add classes onto the Tag.',
                },
                {
                    name: 'style',
                    type: 'object',
                    isRequired: false,
                    default: '',
                    description: 'Add extra styling onto the Tag.',
                },
            ],
        },
    ],
    'react-demo': reactDemo,
};
