import { inputComboGroup, inputSelectComboGroup } from './variations';
import { reactDemo } from './reactDemo';

export default {
    title: 'Input - Combo',
    slug: 'input - combo',
    description: 'Combo inputs are used for commbining input elements with button elements',
    'last-updated': '9/20/21',
    image: '/component_icons/input-combo.svg',
    imageColor: '/component_icons/input-combo_ro.svg',
    variations: [
        {
            name: 'Input Combo Group',
            description: 'Use the class <code class="pier-body-text__inline-code">pier-input-combo</code> to create a default input combo group',
            markup: inputComboGroup,
            dark: false,
        },
        {
            name: 'Input Select Combo Group',
            description: 'Use the class <code class="pier-body-text__inline-code">pier-input-combo</code> to combine multiple select inputs and buttons.',
            markup: inputSelectComboGroup,
            dark: false,
        },
    ],
    'react-import': `import { InputCheckbox } from "pier-design-system"`,
    'react-components': [
        {
            name: '<input checkbox>',
            props: [
                {
                    name: 'children',
                    type: 'node',
                    isRequired: true,
                    default: '',
                    description: 'The content to be displayed inside of the input checkbox.',
                },
                {
                    name: 'name',
                    type: 'string',
                    isRequired: false,
                    default: '',
                    description: 'The name of the checkbox',
                },
                {
                    name: 'checked',
                    type: 'bool',
                    isRequired: false,
                    default: 'false',
                    description: 'Selects an input checked',
                },
                {
                    name: 'indeterminate',
                    type: 'bool',
                    isRequired: false,
                    default: 'false',
                    description: 'Selects an input as partial',
                },
                {
                    name: 'size',
                    type: `string; one of: "sm", "md", "lg"`,
                    isRequired: false,
                    default: 'md',
                    description: 'Set the size of the input checkbox.',
                },
                {
                    name: 'disabled',
                    type: 'bool',
                    isRequired: false,
                    default: false,
                    description: "Set the input checkbox to it's disabled state.",
                },
                {
                    name: 'dark',
                    type: 'bool',
                    isRequired: false,
                    default: false,
                    description: "Set the input checkbox to it's dark theme.",
                },
                {
                    name: 'onChange',
                    type: 'func',
                    isRequired: false,
                    default: '',
                    description: 'Fires the moment when the value of the input checkbox is changed',
                },
                {
                    name: 'value',
                    type: 'string',
                    isRequired: false,
                    default: '',
                    description: '',
                },
                {
                    name: 'error',
                    type: 'bool',
                    isRequired: false,
                    default: 'false',
                    description: 'Makes the input checkbox error',
                },
                {
                    name: 'onClick',
                    type: 'func',
                    isRequired: false,
                    default: '',
                    description: 'Event handler on input checkbox click',
                },
                {
                    name: 'className',
                    type: 'string',
                    isRequired: false,
                    default: '',
                    description: 'Add classes onto the input checkbox',
                },
                {
                    name: 'style',
                    type: 'object',
                    isRequired: false,
                    default: '',
                    description: 'Add extra styling onto the input checkbox.',
                },
                {
                    name: 'onMouseEnter',
                    type: 'func',
                    isRequired: false,
                    default: '',
                    description: 'Event handler on input checkbox hover in',
                },
                {
                    name: 'onMouseLeave',
                    type: 'func',
                    isRequired: false,
                    default: '',
                    description: 'Event handler on input checkbox hover out',
                },
                {
                    name: 'onBlur',
                    type: 'func',
                    isRequired: false,
                    default: '',
                    description: 'Event handler on input checkbox when focus has left the input checkbox',
                },
                {
                    name: 'onFocus',
                    type: 'func',
                    isRequired: false,
                    default: '',
                    description: 'Event handler on input checkbox when on focus',
                },
            ],
        },
    ],
    'react-demo': reactDemo,
};
